# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    paths:
      - '**.cs'
  pull_request:
    paths:
      - '**.cs'
  workflow_dispatch:


jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3.2.0
    - name: Setup .NET
      uses: actions/setup-dotnet@v3.0.3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Upload artifacts
      uses: actions/upload-artifact@v3.1.1
      with:
        name: artifact
        path: D:\a\SNDD\SNDD\SNDD\bin\Release
